require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - "Gemfile"
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "lib/gem_ext/wondeclient/endpoints.rb"
  NewCops: enable

RSpec/NamedSubject:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Exclude:
    - "lib/ext/Wondeclient/**/*.rb"

Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Naming/FileName:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
